import { Consultation2 } from "@/redux/types/consultation";

export const MOCK_CONSULTATIONS: Consultation2[] = [
  {
    id: "CSL-001",
    lawyer: {
      name: "Adaeze Okonkwo",
      initials: "AO",
      color: "#E8317A",
      nbaNumber: "NBA/LAG/2014/01847",
      specialisms: ["Employment Law", "Civil Rights"],
    },
    mode: "message",
    topic: "My landlord locked me out without notice — is this legal?",
    detail: "I came home to find my lock changed. My landlord says I'm behind on rent but I paid last month via transfer.",
    status: "active",
    fee: 5000,
    platformFee: 750,
    createdAt: "Today · 10:14 AM",
    lawyerResponseAt: "Today · 10:52 AM",
    paymentRef: "PAY-20250615-001",
    transcript: [
      {
        id: "m1",
        sender: "citizen",
        senderName: "You",
        text: "I came home to find my lock changed by my landlord. I paid last month's rent — do I have any legal recourse?",
        time: "10:14 AM",
      },
      {
        id: "m2",
        sender: "lawyer",
        senderName: "Adaeze Okonkwo",
        text: "Yes, this is illegal under the Tenancy Law. A landlord cannot forcibly evict you without a court order, regardless of rent disputes. You are entitled to re-entry. I'll outline your options.",
        time: "10:52 AM",
      },
      {
        id: "m3",
        sender: "lawyer",
        senderName: "Adaeze Okonkwo",
        text: "First, send a formal demand letter to the landlord today citing Section 17 of the Lagos Tenancy Law. If he refuses, you can apply for a court order for re-entry. Would you like me to draft the letter?",
        time: "10:54 AM",
      },
    ],
  },
  {
    id: "CSL-002",
    lawyer: {
      name: "Emeka Nwosu",
      initials: "EN",
      color: "#3B82F6",
      nbaNumber: "NBA/ABJ/2012/00934",
      specialisms: ["Property Law", "Business"],
    },
    mode: "call",
    topic: "Wrongful termination — employer refuses to pay severance",
    status: "awaiting_lawyer",
    fee: 12000,
    platformFee: 1800,
    createdAt: "Today · 8:30 AM",
    scheduledAt: "Today · 2:00 PM",
    paymentRef: "PAY-20250615-002",
    transcript: [],
  },
  {
    id: "CSL-003",
    lawyer: {
      name: "Fatimah Bello",
      initials: "FB",
      color: "#8B5CF6",
      nbaNumber: "NBA/KAN/2016/02211",
      specialisms: ["Family Law", "Criminal"],
    },
    mode: "video",
    topic: "Divorce petition — husband refusing to grant access to children",
    status: "completed",
    fee: 18000,
    platformFee: 2700,
    createdAt: "Yesterday · 3:00 PM",
    completedAt: "Yesterday · 4:12 PM",
    paymentRef: "PAY-20250614-003",
    transcript: [],
  },
  {
    id: "CSL-004",
    lawyer: {
      name: "Chidi Okafor",
      initials: "CO",
      color: "#10B981",
      nbaNumber: "NBA/LAG/2015/03102",
      specialisms: ["Business Law", "Consumer Rights"],
    },
    mode: "message",
    topic: "Police detained my brother for 5 days without charges",
    status: "disputed",
    fee: 5000,
    platformFee: 750,
    createdAt: "2 days ago",
    completedAt: "2 days ago",
    paymentRef: "PAY-20250613-004",
    disputed: true,
    disputeReason: "The advice provided did not address the specific charges mentioned. The lawyer suggested a general approach that was not applicable.",
    transcript: [],
  },
  {
    id: "CSL-005",
    lawyer: {
      name: "Ngozi Eze",
      initials: "NE",
      color: "#F59E0B",
      nbaNumber: "NBA/PHC/2017/01563",
      specialisms: ["Employment Law"],
    },
    mode: "call",
    topic: "Business registration dispute — partner withdrew all capital",
    status: "completed",
    fee: 12000,
    platformFee: 1800,
    createdAt: "3 days ago",
    completedAt: "3 days ago",
    paymentRef: "PAY-20250612-005",
    rating: 4,
    ratingNote: "Very helpful, explained my options clearly. Would use again.",
    transcript: [],
  },
];
