import { Consultation, MatchRequest } from "@/redux/types/consultation";

export const MOCK_CONSULTATIONS: Consultation[] = [
  {
    id: "CSL-001",
    citizen: { id: "asdfddf", name: "Chidinma Okafor", initials: "CO", color: "#E8317A", state: "Enugu" },
    mode: "message",
    topic: "My landlord locked me out without notice — is this legal?",
    fee: 5000,
    platformFee: 750,
    lawyerPayout: 4250,
    status: "awaiting_lawyer",
    createdAt: "Today · 10:14 AM",
  },
  {
    id: "CSL-002",
    citizen: { id: "asdfddf", name: "Babatunde Lawal", initials: "BL", color: "#3B82F6", state: "Lagos" },
    mode: "call",
    topic: "Wrongful termination — employer refuses to pay severance",
    fee: 12000,
    platformFee: 1800,
    lawyerPayout: 10200,
    status: "active",
    createdAt: "Today · 8:30 AM",
    scheduledAt: "Today · 2:00 PM",
  },
  {
    id: "CSL-003",
    citizen: { id: "asdfddf", name: "Amina Garba", initials: "AG", color: "#8B5CF6", state: "Kano" },
    mode: "video",
    topic: "Divorce petition — husband refusing to grant access to children",
    fee: 18000,
    platformFee: 2700,
    lawyerPayout: 15300,
    status: "completed",
    createdAt: "Yesterday · 3:00 PM",
    completedAt: "Yesterday · 4:12 PM",
    rating: 5,
    ratingNote: "Very professional and knowledgeable. Explained everything clearly.",
  },
  {
    id: "CSL-004",
    citizen: { id: "asdfddf", name: "Ikechukwu Eze", initials: "IE", color: "#10B981", state: "Rivers" },
    mode: "message",
    topic: "Police detained my brother for 5 days without charges",
    fee: 5000,
    platformFee: 750,
    lawyerPayout: 4250,
    status: "disputed",
    createdAt: "2 days ago",
    disputed: true,
    disputeReason: "Citizen ,aims advice given was insufficient and incorrect.",
  },
  {
    id: "CSL-005",
    citizen: { id: "asdfddf", name: "Ngozi Eze", initials: "NE", color: "#F59E0B", state: "Anambra" },
    mode: "call",
    topic: "Business registration dispute — partner withdrew all capital",
    fee: 12000,
    platformFee: 1800,
    lawyerPayout: 10200,
    status: "completed",
    createdAt: "3 days ago",
    completedAt: "3 days ago",
    rating: 4,
    ratingNote: "Good advice but response was slightly delayed.",
  },
  {
    id: "CSL-006",
    citizen: { id: "asdfddf", name: "Emeka Nwosu", initials: "EN", color: "#EF4444", state: "Abuja" },
    mode: "message",
    topic: "Landlord refusing to return ₦200k security deposit",
    fee: 5000,
    platformFee: 750,
    lawyerPayout: 4250,
    status: "cancelled",
    createdAt: "4 days ago",
  },
];

export const MOCK_MATCH_REQUESTS: MatchRequest[] = [
  {
    id: "MR-001",
    citizen: { id: "asdfddf", name: "Fatimah Bello", initials: "FB", color: "#06B6D4", state: "Kaduna" },
    specialism: "Employment Law",
    urgency: "Today",
    budget: "NGN 5,000 – 15,000",
    description: "I was dismissed from my job without any written notice. My employer claims I violated company policy but refuses to show the clause.",
    status: "pending",
    createdAt: "30 mins ago",
    expiresAt: "In 23 hrs",
  },
  {
    id: "MR-002",
    citizen: { id: "asdfddf", name: "Abubakar Sadiq", initials: "AS", color: "#7C3AED", state: "Kano" },
    specialism: "Criminal Law",
    urgency: "This week",
    budget: "NGN 5,000 – 15,000",
    description: "My nephew was arrested during a protest. He has been in detention for 4 days without being charged. Need legal advice urgently.",
    status: "pending",
    createdAt: "2 hrs ago",
    expiresAt: "In 22 hrs",
  },
];
