import {
  Search, Filter, MapPin, Star, Clock, Shield, Zap,
  CheckCircle, MessageSquare, Video, Phone, Calendar,
  ChevronRight, ChevronDown, X, ArrowRight, Send,
  BadgeCheck, Award, TrendingUp, Users, Lock,
  FileText, AlertCircle, ChevronLeft, Loader2,
  SlidersHorizontal, BookOpen, Briefcase, Building2,
  Scale, Home, Heart, Car, Globe, Check, Plus,
  Bell, UserPlus, ClipboardList, Sparkles, Info,
} from "lucide-react";
import { ConsultMode, Lawyer } from "./types";

export const SPECIALISMS = [
  { id: "all",        label: "All Areas",        icon: Scale },
  { id: "criminal",   label: "Criminal Law",      icon: Shield },
  { id: "property",   label: "Property & Tenancy",icon: Home },
  { id: "employment", label: "Employment",         icon: Briefcase },
  { id: "business",   label: "Business & CAC",     icon: Building2 },
  { id: "family",     label: "Family Law",         icon: Heart },
  { id: "consumer",   label: "Consumer Rights",    icon: Globe },
  { id: "road",       label: "Road Traffic",       icon: Car },
];

export const LAWYERS: Lawyer[] = [
  {
    id: "l1",
    name: "Adaeze Okonkwo",
    initials: "AO",
    colorA: "#1E3A5F",
    colorB: "#2D5A8E",
    title: "Criminal & Civil Rights Lawyer",
    specialisms: ["criminal", "employment"],
    location: "Victoria Island",
    state: "Lagos",
    rating: 4.9,
    reviewCount: 84,
    responseTime: "Under 1 hour",
    consultations: 312,
    fee: { message: 5000, call: 12000, video: 18000 },
    badges: ["Verified Lawyer", "Top Rated", "Responsive"],
    available: true,
    bio: "Called to the Nigerian Bar in 2014 with a focus on criminal defence, police accountability, and fundamental rights enforcement. Regularly appears before the Federal High Court and Court of Appeal.",
    yearsCall: 10,
    languages: ["English", "Igbo"],
    nbaNumber: "NBA/LAG/2014/01847",
  },
  {
    id: "l2",
    name: "Emeka Nwosu",
    initials: "EN",
    colorA: "#1A3B2E",
    colorB: "#2D6A4F",
    title: "Property & Tenancy Lawyer",
    specialisms: ["property", "business"],
    location: "Wuse II",
    state: "Abuja",
    rating: 4.8,
    reviewCount: 112,
    responseTime: "Under 2 hours",
    consultations: 487,
    fee: { message: 4500, call: 10000, video: 15000 },
    badges: ["Verified Lawyer", "Top Rated"],
    available: true,
    bio: "Senior associate with 12 years in property transactions, landlord-tenant disputes, and commercial leases across Abuja and Lagos. Former in-house counsel at a major property development firm.",
    yearsCall: 12,
    languages: ["English", "Igbo", "Yoruba"],
    nbaNumber: "NBA/ABJ/2012/00934",
  },
  {
    id: "l3",
    name: "Fatimah Bello",
    initials: "FB",
    colorA: "#2D1A3B",
    colorB: "#4A2D6A",
    title: "Family & Domestic Rights Lawyer",
    specialisms: ["family", "criminal"],
    location: "GRA",
    state: "Kano",
    rating: 4.7,
    reviewCount: 56,
    responseTime: "Under 3 hours",
    consultations: 198,
    fee: { message: 4000, call: 9000, video: 14000 },
    badges: ["Verified Lawyer", "Responsive"],
    available: false,
    bio: "Specialist in domestic violence protection orders, child custody, matrimonial causes, and gender-based violence law. Founding member of the Kano Women's Legal Access Initiative.",
    yearsCall: 8,
    languages: ["English", "Hausa", "Fulfulde"],
    nbaNumber: "NBA/KAN/2016/02211",
  },
  {
    id: "l4",
    name: "Chidi Okafor",
    initials: "CO",
    colorA: "#1A2D3B",
    colorB: "#0E4D6A",
    title: "Business & Commercial Lawyer",
    specialisms: ["business", "consumer"],
    location: "Ikeja",
    state: "Lagos",
    rating: 4.6,
    reviewCount: 73,
    responseTime: "Under 2 hours",
    consultations: 254,
    fee: { message: 6000, call: 15000, video: 22000 },
    badges: ["Verified Lawyer", "Top Rated"],
    available: true,
    bio: "Corporate and commercial lawyer advising SMEs on business registration, contracts, IP, and consumer protection. Previously worked at a top-tier Lagos commercial law firm for 7 years.",
    yearsCall: 9,
    languages: ["English", "Igbo"],
    nbaNumber: "NBA/LAG/2015/03102",
  },
  {
    id: "l5",
    name: "Ngozi Eze",
    initials: "NE",
    colorA: "#2D1A1A",
    colorB: "#7B2828",
    title: "Employment & Labour Lawyer",
    specialisms: ["employment", "consumer"],
    location: "Trans-Amadi",
    state: "Rivers",
    rating: 4.8,
    reviewCount: 49,
    responseTime: "Under 1 hour",
    consultations: 163,
    fee: { message: 4500, call: 11000, video: 16000 },
    badges: ["Verified Lawyer", "Responsive"],
    available: true,
    bio: "Focuses exclusively on employment law: wrongful termination claims, NSITF disputes, workplace harassment, and industrial arbitration. Represents workers at the National Industrial Court.",
    yearsCall: 7,
    languages: ["English", "Igbo"],
    nbaNumber: "NBA/PHC/2017/01563",
  },
  {
    id: "l6",
    name: "Abubakar Sadiq",
    initials: "AS",
    colorA: "#2A2D1A",
    colorB: "#5A6A2D",
    title: "Property & Road Traffic Lawyer",
    specialisms: ["property", "road"],
    location: "Barnawa",
    state: "Kaduna",
    rating: 4.5,
    reviewCount: 38,
    responseTime: "Under 4 hours",
    consultations: 121,
    fee: { message: 3500, call: 8000, video: 12000 },
    badges: ["Verified Lawyer"],
    available: true,
    bio: "General practice with particular depth in Northern Nigerian property law, title registration, and road traffic accident claims. Experienced in multi-party negotiations and out-of-court settlement.",
    yearsCall: 6,
    languages: ["English", "Hausa"],
    nbaNumber: "NBA/KAD/2018/00789",
  },
];


export const BADGE_STYLE: Record<string, { bg: string; text: string; border: string }> = {
  "Verified Lawyer": { bg: "#FFFBEB", text: "#92400E", border: "#FDE68A" },
  "Top Rated":       { bg: "#ECFDF5", text: "#065F46", border: "#6EE7B7" },
  "Responsive":      { bg: "#EFF6FF", text: "#1E3A8A", border: "#93C5FD" },
};

export const BADGE_ICON: Record<string, React.ElementType> = {
  "Verified Lawyer": BadgeCheck,
  "Top Rated":       Award,
  "Responsive":      Zap,
};

export const CONSULT_MODES: { id: ConsultMode; label: string; icon: React.ElementType; desc: string }[] = [
  { id: "message", label: "Written Message",  icon: MessageSquare, desc: "Async,  reply within response time" },
  { id: "call",    label: "Scheduled Call",   icon: Phone,         desc: "Audio call, you pick the time slot" },
  { id: "video",   label: "Video Session",    icon: Video,         desc: "Face-to-face via secure video link" },
];